// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKNu47c3HDnEWUqiXF3CM_1j121JN1mo',
    appId: '1:1006240780546:web:9337592ba8f8a7340eb21b',
    messagingSenderId: '1006240780546',
    projectId: 'instavid-e4f00',
    authDomain: 'instavid-e4f00.firebaseapp.com',
    storageBucket: 'instavid-e4f00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlQ_g3zI94EWp20o6G_c6_-hxCzvx8Sk',
    appId: '1:1006240780546:android:ad43125ddf6d55f80eb21b',
    messagingSenderId: '1006240780546',
    projectId: 'instavid-e4f00',
    storageBucket: 'instavid-e4f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRObIlp9QXDNVBtZxItKeTuSmkmqiSRs',
    appId: '1:1006240780546:ios:beb09b80c2205a840eb21b',
    messagingSenderId: '1006240780546',
    projectId: 'instavid-e4f00',
    storageBucket: 'instavid-e4f00.appspot.com',
    iosClientId: '1006240780546-mb7cn7jlshin0f4995r19ku7m7k7fnbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.todo',
  );
}
